binary_sensor:
  - platform: status
    name: Online
    id: ink_ha_connected

  - platform: ld2410
    has_target:
      name: Presence
      id: ld2410_has_target
      # on_state:
      #   then:
      #     - component.update: presence_filtered   # ❌ binary_sensor nie wspiera update
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target

  - platform: gpio
    name: "OUT Pin"
    id: ld2410_out_pin
    pin:
      number: GPIO16
      mode:
        input: true
        pullup: false
      inverted: false
    device_class: motion

  - platform: template
    id: presence_filtered
    name: "Presence ≤ 2.2m"
    device_class: occupancy
    filters:
      - delayed_off: 3s
    lambda: |-
      // brak targetu = brak obecności
      if (!id(ld2410_has_target).state) {
        return false;
      }

      // dystans nieznany lub 0 → uznaj jako obecność
      if (!id(detection_distance).has_state() || id(detection_distance).state <= 0) {
        return true;
      }

      // UWAGA: detection_distance jest w CM
      return id(detection_distance).state <= 220;
