# =======================
# BINARY SENSORS
# =======================
binary_sensor:
  - platform: status
    name: Online
    id: ink_ha_connected

  - platform: ld2410
    has_target:
      name: Presence
      id: ld2410_has_target
    has_moving_target:
      name: Moving Target
      id: has_moving_target
    has_still_target:
      name: Still Target
      id: has_still_target

  - platform: gpio
    name: "OUT Pin"
    id: ld2410_out_pin
    pin:
      number: GPIO16
      mode:
        input: true
      inverted: false
    device_class: motion
