sensor:
  - platform: internal_temperature
    id: sys_esp_temperature
    name: ESP Temperature
    unit_of_measurement: °C
    device_class: TEMPERATURE
    update_interval: 45s
    entity_category: diagnostic

  - platform: uptime
    name: Uptime
    id: sys_uptime
    update_interval: 10s

  - platform: wifi_signal 
    name: RSSI
    id: wifi_signal_db
    update_interval: 5s
    entity_category: diagnostic

  - platform: template
    id: esp_memory
    name: ESP Free Memory
    lambda: return heap_caps_get_free_size(MALLOC_CAP_INTERNAL) / 1024;
    unit_of_measurement: kB
    entity_category: diagnostic

  - platform: ld2410
    moving_distance:
      name: Moving Distance
      id: moving_distance
    still_distance:
      name: Still Distance
      id: still_distance
    moving_energy:
      name: Move Energy
    still_energy:
      name: Still Energy
    detection_distance:
      name: Detection Distance
      id: detection_distance
      force_update: true
      # on_value:
      #   then:
      #     - component.update: presence_zone_1  # ❌ niedozwolone
